services: 
  - docker

install:
  - sudo apt-get install -y jq
  - ./unit-test/create_user.sh && cp id_user unit-test/

jobs:
  include:
    - stage: "Test environment var"
      name: "Test environment var"
      script: ls; cat unit-test/id_user
    - stage: "Build Docker"
      name: "Build Docker"
      script: docker-compose build && docker-compose up -d
      after_script:
        - docker-compose ps
    - stage: "Tests users"
      script: cat unit-test/id_user
      name: "get users"
    - script: ./unit-test/get_user.sh && ./unit-test/get_user_by_id.sh && ./unit-test/update_user.sh && ./unit-test/create_clock.sh && ./unit-test/get_clock.sh && ./unit-test/delete_user.sh
      name: test

after_script:
    - cat dumps.txt
    - rm dumps.txt

stages:
    - Test environment var
    - Tests users
    - Build Docker

notifications:
  webhooks: https://outlook.office.com/webhook/fda60e47-d851-46da-9879-4a6c58bbfc04@901cb4ca-b862-4029-9306-e5cd0f6d9f86/TravisCI/7ca4246150114f65a5b731008b9d8bc6/c755656a-9f25-4fa1-8c17-f1c880043093
