services: 
  - docker

before-script:
  - sudo apt-get install -y jq

env:
  global:
    - ID_USER=$(./unit-test/create_user.sh)

jobs:
  include:
    - stage "Test environment var"
      name "Test env var"
      script env | grep "ID_USER"
    - stage: "Build Docker"
      name: "Build Docker"
      script: docker-compose build && docker-compose up -d
      after_script:
        - docker-compose ps
    - stage: "Tests users"
      script: env | grep "ID_USER" && ./unit-test/get_user.sh
      name: "get users"
    - script: env | grep "ID_USER" && ./unit-test/get_user_by_id.sh
      name: "get users by  id"
    - script: env | grep "ID_USER" && ./unit-test/update_user.sh
      name: "update user"
    - stage: "Tests clocks"
      name: "create clock in"
      script: env | grep "ID_USER" && ./unit-test/create_clock.sh
    - script : env | grep "ID_USER" && ./unit-test/create_clock.sh
      name: "create clock out"
    - script: env | grep "ID_USER" && ./unit-test/get_clock.sh
      name: "Get clock"
    - stage: "Delete user"
      script: env | grep "ID_USER" && ./unit-test/delete_user.sh
      name: "delete user"


after_script:
    - cat dumps.txt
    - rm dumps.txt

stages:
    - Test environment var
    - Tests users
    - Tests clocks
    - Build Docker

notifications:
  webhooks: https://outlook.office.com/webhook/fda60e47-d851-46da-9879-4a6c58bbfc04@901cb4ca-b862-4029-9306-e5cd0f6d9f86/TravisCI/7ca4246150114f65a5b731008b9d8bc6/c755656a-9f25-4fa1-8c17-f1c880043093
