version: '3.3'
services:

  phoenix:
    build:
      context: ./back-end
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment: 
      - DATABASE_URL=ecto://postgres:postgres@db:5432/working_time_manager_dev

  db:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - PGDATABASE=working_time_manager_dev
      - PGUSER=postgres
      - PGPASSWORD=postgres
  
  front:
    build:
      context: ./front-end
    restart: unless-stopped
    depends_on:
      - phoenix
    ports:
      - "80:80"

volumes:
  build:
  dbdata:
    external: false
