version: '3.3'
services:

  phoenix:
    build:
      context: ./working_time_manager
      dockerfile: ./docker-resources/Dockerfile-Backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "80:80"
    environment: 
      - DATABASE_URL=ecto://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}
    links:
      - "db:database"

  db:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped
    command: -p ${PGPORT}
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}

volumes:
  dbdata:
    external: false
