FROM elixir:1.8.2-otp-22

RUN apt -y update ; \
    apt -y install nodejs; \
    apt -y clean

COPY . /working_time_manager

RUN cd /working_time_manager; \
    mix local.hex --force; \
    mix local.rebar --force; \
    mix deps.get --only prod

ENV DATABASE_URL=ecto://postgres:postgres@database/database
ENV SECRET_KEY_BASE=XRpZ+3dLc8bJnzMdFwJl7mcKrW+UBr/Vwf1otPKW3YG7KmsVKt6Zg6mUndkLs/7x
ENV PGDATABASE="database"
ENV PGUSER="postgres"
ENV PGPASSWORD="postgres"
ENV PGDATABASE="db"

RUN cd /working_time_manager; \
    MIX_ENV=prod mix compile

RUN env

COPY ./docker-resources/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
